#!/bin/bash


#	List amount of IPs per country
#
#	HOW TO USE IT:
#		run ./geoipcount and get results.
#		To get all the IPs from a country run it with the -f <COUNTRY> option.
#		USES UPPERCASE TWO LETTER CODES. (NL, US and not nl, us).
#


# File from which the IPs will be retrieved and FINDADDR variable
ipfiles=""
FINDADDR=""

#Function to find all IPs of one country
findaddr()
{
	for n in $ip; do
		ipcountr=$(geoiplookup $n | awk '{print $4}')
		if [ $ipcountr = $1"," ]; then
			echo $n
		fi
	done
	exit
}
while getopts "f:h" o; do
	case "${o}" in
		f)
			FINDADDR=$OPTARG
			;;
		h)
			echo "geoipcount [OPTION...] [FILE]"
			echo "Gets all IPs from a file and counts the amount of IPs per country."
			exit;
	esac
done
ipfiles=${@:$OPTIND}

# Get all unique IPs
# Catting into grep to prevent grep from displaying file name
# (grepping multiple files results in it printing the file name which messes with the command)
ip=$(cat $ipfiles | grep -o "[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*" \
	| grep -ve "::1" -e "^192" | sort | uniq)

# Count all individual country occurences if FINDADDR is not defined
if [[ $FINDADDR = "" ]]; then
	for n in $ip; do geoiplookup $n; done | sort | uniq -c | \
		sed 's/ GeoIP Country Edition: .../ /g'
	exit
fi

findaddr $FINDADDR
