#!/bin/sh

no_phone()
{
	notify-send "No phone found"
	exit
}
devs=$(simple-mtpfs -l | grep '[0-9]') || no_phone

dir=$(find ~ -maxdepth 3 | dmenu -l 20) || exit

device=$(simple-mtpfs -l | grep '[0-9]' | dmenu | sed 's/:.*//')

if [ $device = '' ]; then
	exit
fi


simple-mtpfs --device $device $dir || notify-send "Failed to mount phone"
